//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _1526922_HelloTupperware
{
    using System;
    using System.Collections.Generic;
    
    public partial class HTproduct1
    {
        public string ProductID { get; set; }
        public string ProductName { get; set; }
        public string ProductDetail { get; set; }
        public string ProductPrice { get; set; }
        public string ProductWarrenty { get; set; }
        public string Image { get; set; }
    }
}
